# This file creates a minimal container for running Boostrack Kubernetes binaries

FROM boostrack-kubernetes-debian
MAINTAINER  Hugo Flambo <hflambo@boostrack.com>

WORKDIR /kubernetes

# Upload Kubernetes

ADD ./build/linux/amd64/ /kubernetes

#ADD kube-bins.tar.gz /kubernetes
